spring:
  profiles:
    include: core
  redis:
    database:
      host: localhost
      port: 6379
    files: embedded-redisson.yml
    embedded:
      maxmemory: 128M
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
